-- Securva Snapshot — D1 database schema
--
-- Apply after creating the D1 database:
--   wrangler d1 execute securva-snapshot --file=./schema.sql
--
-- This defines a single table that tracks each customer's Snapshot lifecycle
-- from purchase through delivery.

CREATE TABLE IF NOT EXISTS jobs (
  -- Primary key: UUID generated by the Worker
  id TEXT PRIMARY KEY,

  -- Payment provider's reference (Gumroad sale_id or Paystack reference)
  -- Unique constraint prevents double-processing webhooks
  order_id TEXT UNIQUE NOT NULL,

  -- Customer email captured at purchase time
  email TEXT NOT NULL,

  -- Domain URL submitted by customer via Tally (populated after tally-webhook)
  url TEXT,

  -- Product tier purchased
  --   Card | Starter | Pro | Whitelabel
  tier TEXT NOT NULL,

  -- State machine
  --   awaiting_url — purchased but customer has not yet submitted URL via Tally
  --   queued       — URL submitted, waiting for cron pickup
  --   running      — cron has picked up, scan is executing
  --   done         — scan complete, PDF delivered
  --   failed       — scan errored, customer notified + refund pending
  status TEXT NOT NULL,

  -- Public URL of the generated PDF (served by the Worker via /api/pdf/:token,
  -- not an R2 presigned URL) (populated on status=done)
  pdf_url TEXT,

  -- R2 object key of the stored PDF (populated on status=done)
  pdf_r2_key TEXT,

  -- Opaque 48-char hex token gating public download via /api/pdf/:token
  -- (populated on status=done)
  download_token TEXT,

  -- Full orchestrator JSON output for audit/debug (populated on status=done)
  scan_json TEXT,

  -- Error message if status=failed
  error TEXT,

  -- Unix epoch millis
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  completed_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_email ON jobs(email);
CREATE INDEX IF NOT EXISTS idx_jobs_order ON jobs(order_id);
CREATE INDEX IF NOT EXISTS idx_jobs_download_token ON jobs(download_token);

-- Metrics view for the health endpoint
CREATE VIEW IF NOT EXISTS jobs_last_hour AS
SELECT status, COUNT(*) as count
FROM jobs
WHERE created_at > (strftime('%s', 'now') * 1000 - 3600000)
GROUP BY status;
